### ISSUE TITLE
HDF 1.14 + netcdf-c 4.9 Support?

### ISSUE THREAD

**Issue by akrherz** [Unidata/netcdf-cxx4#132]
I'm attempting to build netcdf-cxx4 against HDF5 1.14.0 and netcdf-c 4.9.1 for conda-forge/netcdf-cxx4-feedstock#43 and am getting a test failure

>      Start 10: cxx4_test_filter
> 10/18 Test 10: cxx4_test_filter .................***Failed    0.01 sec

Is a release of netcdf-cxx4 coming to support these updated releases?

**Comment by ZedThree** [comment]
Is this fixed by #138? If so, it's not actually an incompatibility with hdf5 1.14, so you can safely use it

**Comment by akrherz** [comment]
Hi @ZedThree, I am unsure.  I have bumped conda-forge/netcdf-cxx4-feedstock#43 to get a current build failure.

**Comment by akrherz** [comment]
well it seems my troubles went away when using HDF5 1.14.3 and libnetcdf 4.9.2, shrug!
