### ISSUE TITLE
Is netCDF-C 4.3.3 compatible?

### ISSUE THREAD

**Issue by qubotong** [Unidata/netcdf-cxx4#24]
Hello,

I'm using VS 2013 + pre-built netCDF-C 4.3.3 lib to run this example. But the compiler keeps telling me that some unresolved external symbols. Do you have any similar report or any solutions? Or it just because I didn't link the dll and lib correctly, do you have some detailed installment instruction.

**Comment by citibeth** [comment]
Would you be able to provide the error log from the linker?

**Comment by qubotong** [comment]
Thanks a lot for your reply, I found out the problem. It's because I'm using x64 lib which is wrong. Thanks again
