### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by 5tefan** [Unidata/netcdf-cxx4#27]
Links to online documentation from the top of example files are dead:

> Full documentation of the netCDF C++ API can be found at:
> http://www.unidata.ucar.edu/software/netcdf/docs/netcdf-cxx

Unfortunately, some search engines are also linking there for queries on netCDF C++ documentation and some internal Unidata links point there.

<del>Also the directory cxx4 from * has no Doxyfile so running ```doxygen``` as instructed by the README does nothing. </del>    

*Edit: My mistake, I was building from the release linked here http://www.unidata.ucar.edu/downloads/netcdf/netcdf-cxx/index.jsp, which is little out of date.

**Comment by 5tefan** [comment]
Basically, the Unidata website is frustrating/dated.

**Comment by WardF** [comment]
I'll address this as best I can; the netcdf documentation is undergoing as reorganization as of last week, and a few things have cropped up (like this).  I'll address it as quickly as I can, although we're a bit resource constrained.

**Comment by 5tefan** [comment]
Awesome! Thanks for the info. It's good to hear it is a side effect rather than neglect.
