### ISSUE TITLE
Should ncAtt.cpp_keep be in the repo?

### ISSUE THREAD

**Issue by citibeth** [Unidata/netcdf-cxx4#28]
https://github.com/Unidata/netcdf-cxx4/blob/f10f1abbbbc2a4a8c6cfe645ac639966222e3e5d/cxx4/ncAtt.cpp_keep

**Comment by WardF** [comment]
Probably not; there is at least one other `_keep` file, for some reason.  I'll go through and do some cleanup, now that I've gotten the C and Fortran releases out of the way, C++ `4.3.0` will be next.

**Comment by WardF** [comment]
Cleaned these up in `master`, so closing out the issue.
