### ISSUE TITLE
ncxx4-config missing in cmake-build

### ISSUE THREAD

**Issue by kmuehlbauer** [Unidata/netcdf-cxx4#36]
Version 4.3.0

Everything builds fine with `cmake`, but the ncxx4-config file isn't generated. Will this be added in the near future or do we have to switch back to `configure`?

**Comment by kmuehlbauer** [comment]
I'm not sure, if the proposed fix fits nicely into the cmake-build. Runs well on my linux-box.

**Comment by WardF** [comment]
Closed as the associated pull request has been merged! Thanks again!
