### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by 5tefan** [Unidata/netcdf-cxx4#42]
I would reopen #27 if I could, as the Unidata website remains in unfortunate condition. 

The situation could be slightly improved by providing the C++ interface documentation via Github Pages. Since the `docs/` dir is occupied, the easiest way to do this is probably with a `gh-pages` branch.

I've published the documentation on [my own fork](https://5tefan.github.io/netcdf-cxx4/namespaces.html).  It would be better to have that available from this repo though. 

Having run Doxygen and with [gh-pages](https://www.npmjs.com/package/gh-pages) installed from the nodejs ecosystem, publishing the documentation is as simple as
```bash
gh-pages -d cxx4/doc/html/
```

Please consider doing this! Thanks.

**Comment by WardF** [comment]
Reopened as you are quite right. Let me look at gh pages and see if that meets the requirements of our web admins

**Comment by WardF** [comment]
I couldn't get gh-pages to work but I did get the documentation here:

* http://unidata.github.io/netcdf-cxx4/index.html

I'll need to update the links and references external to this, but closing out this issue for now.

**Comment by 5tefan** [comment]
Looks great! Thanks!
