### ISSUE TITLE
CMake Config files missing on install.

### ISSUE THREAD

**Issue by ftpronk** [Unidata/netcdf-cxx4#43]
It seems that the current code is missing the correct CMake files allowing the netCDFCxx package to be found in other projects.  This is the error returned by ccmake:

>CMake Error at CMakeLists.txt:100 (find_package):
>   By not providing "FindnetCDFCxx.cmake" in CMAKE_MODULE_PATH this project
>   has asked CMake to find a package configuration file provided by
>   "netCDFCxx", but CMake did not find one.
>
>   Could not find a package configuration file provided by "netCDFCxx" with
>   any of the following names:
>
>     netCDFCxxConfig.cmake
>     netcdfcxx-config.cmake
>
>   Add the installation prefix of "netCDFCxx" to CMAKE_PREFIX_PATH or set
>   "netCDFCxx_DIR" to a directory containing one of the above files.  If
>   "netCDFCxx" provides a separate development package or SDK, be sure it has
>   been installed.

After being called in CMakeLists with:
`find_package(netCDFCxx REQUIRED)`
`include_directories(${NETCDFCxx_INCLUDE_PATH})`

The netCDFCxx installer only installs the CMake file `netCDFCxxConfigVersion.cmake` in:
`./lib64/cmake/netCDFCxx`

**Comment by WardF** [comment]
thanks; reviewing this!

**Comment by ArchangeGabriel** [comment]
Note this is an issue with both CMake and autotools builds, the latest does not even install any CMake files.
