### ISSUE TITLE
How do I get format type

### ISSUE THREAD

**Issue by Weiming-Hu** [Unidata/netcdf-cxx4#49]
It looks like there is no [getFormat](http://www.nrel.colostate.edu/projects/irc/public/Documents/Software/netCDF/cpp4/html/classnetcdf_1_1NcFile.html#ae98ceae63320e7f550cee18bc8cd0f72) as in NetCDF 4.4.1

So can I do it in NetCD 4.3?

Thank you

**Comment by DennisHeimbigner** [comment]
You man have to use the C function nc_inq_format directly.

**Comment by Weiming-Hu** [comment]
Thank you.

**Comment by Weiming-Hu** [comment]
A follow up question.

I'm reading a NetCDF file with unknown structure, and I'd like to read the values of the attribtues. I'm aware that I can use getAttType to get the type, and then allocate memory. But what would the proper way to do this automatically. Do I need to write a template?

Thank you.
