### ISSUE TITLE
build netcdf 4.4.1 for netcdf-cxx4

### ISSUE THREAD

**Issue by jcwright77** [Unidata/netcdf-cxx4#50]
the flag, configure --enable-cxx-4, no longer exists for netcdf 4. how to build for cxx interface ?

**Comment by WardF** [comment]
You first install the netcdf-c core library (available from https://github.com/Unidata/netcdf-c) and then install this code, which provides an interface to the core C library.  The configure/cmake tools will locate and link against the C library.

**Comment by jcwright77** [comment]
thanks. i did get that to work. the confusion is that the flag referred to in the readme --enable-cxx-4 no longer exists in the latest releases.

-john

On Sep 25, 2017, at 7:03 PM, Ward Fisher <notifications@github.com<mailto:notifications@github.com>> wrote:


You first install the netcdf-c core library (available from https://github.com/Unidata/netcdf-c) and then install this code, which provides an interface to the core C library. The configure/cmake tools will locate and link against the C library.

**Comment by dlg0** [comment]
Just following up on this, I too was confused by the readme since it suggests using the --enable-cxx-4 flag on the configure for netcdf-cxx4 build. Perhaps updating the readme is in order. Thanks.

**Comment by WardF** [comment]
Thank you very much; I will correct this for the upcoming release.  The issue is that the documentation was never updated when the C/Fortran/C++ interfaces were separated into individual libraries.  Thanks for letting me know @dlg0 and @jcwright77 !
